<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
 xmlns:xs="http://www.w3.org/2001/XMLSchema"
 targetNamespace="http://schemas.animation.org/xsheet/otio"
 xmlns="http://schemas.animation.org/xsheet/otio"
 elementFormDefault="qualified">

 <xs:element name="OTIO">
     <xs:complexType>
         <xs:sequence>
             <xs:element name="TimelineRef" type="xs:string"/>
             <xs:element name="TrackMap"
                         type="TrackMapType"
                         minOccurs="0"
                         maxOccurs="unbounded"/>
         </xs:sequence>
     </xs:complexType>
 </xs:element>

 <xs:complexType name="TrackMapType">
     <xs:attribute name="xsheetLayer" type="xs:string" use="required"/>
     <xs:attribute name="otioTrack" type="xs:string" use="required"/>
 </xs:complexType>

</xs:schema>
